Initial commit
MetLifeLegalPlans/sign-here pull request #1
Opened 2021-06-02 14:22 UTC by knitHacker

Can install it locally and import the module successfully.

2021-06-02 20:04 UTC, markrawls requested changes
Also I'm about 80% confident we can't (and 100% certain we shouldn't) legally host the Century Expanded Bold font file here. That and I don't think the general public using this library would be needing that. Overall though, coming along nicely!!

2021-06-02 20:04 UTC, markrawls commented on tests/test_image_adding.py
> +import pytest
Not a change request, but +200 points to you for using `pytest` and including unit tests in v1

2021-06-02 20:04 UTC, markrawls commented on signhere/utils.py
> +DEFAULT_SCALAR = 0.75
Dumb question - what's this for?

2021-06-02 20:11 UTC, cviveiro commented on signhere/utils.py
> +DEFAULT_SCALAR = 0.75
i found that this was the scaling needed in the x and y direction to get things placed correctly. this is scaling from the (x, y) coords we get from pdf gen to the (x, y) coords we need to use to place the picture in the right place on the pdf

2021-06-03 15:03 UTC, knitHacker commented on README.md
> +signhere.utils.
haha sorry i didn't actually know how to use it so i stopped in the middle of the example.

2021-06-03 15:06 UTC, knitHacker commented
Thanks! Will remove the font and make suggested code changes. So far I hadn't really touched the code other than update the import in tests.

2021-06-03 15:09 UTC, knitHacker commented on tests/test_image_adding.py
> +import pytest
hahaha don't give me credit for it. it was with the initial code in doc-gen

2021-06-07 16:18 UTC, knitHacker commented on signhere/utils.py
> +    loader_args=None,
do you want type annotations on all function arguments or just the public ones?

2021-06-07 17:20 UTC, knitHacker commented on README.md
> +signhere.utils.
just to clarify you want to ditch the README.md and substitute something generated by sphinx? so I would check in the generate documentation?

2021-06-08 15:51 UTC, knitHacker commented
@markrawls would appreciate another look through. I cleaned up the code / added in sphinx type docstrings and added in sphinx docs. Still have the readme because not sure how / if I should use generated (and checked in) sphinx docs for the readme

2021-06-08 20:41 UTC, markrawls commented on signhere/utils.py
> +    loader_args=None,
Ideally all of them, but if it becomes too cumbersome then we can ditch annotating private members.

2021-06-08 20:54 UTC, markrawls commented on README.md
> +signhere.utils.
Yep! I'd say check in the source files and set up a ReadTheDocs page for it, don't commit the generated documentation.

2021-06-08 22:17 UTC, markrawls requested changes
Outside of that, looks good!!

2021-06-08 22:17 UTC, markrawls commented on docs/conf.py
> +author = "Mark Rawls"
This should probably be your name (or the company's) instead of mine

2021-06-10 13:22 UTC, knitHacker commented on docs/conf.py
> +author = "Mark Rawls"
I can put the companies name but all the actual code was written by you and christine wrote all the actual code haha

2021-06-10 14:41 UTC, knitHacker commented
Glad I went to add type annotations to the private functions because I realized I didn't remove the references to the IMAGE_CONSTANTS dict that I removed.

2021-06-14 20:01 UTC, markrawls approved these changes
This is beautiful. Great job on that! We should make a ReadTheDocs org (if that's a thing they offer) and get our docs for this hosted there, but this is more than enough to get started.

2021-06-14 20:02 UTC, merged